version: 2
jobs:
  indigo:
    docker:
      - image: ros:indigo-ros-core
    steps:
      - checkout
      - run:
          command: |
            apt-get update && apt-get install openssh-client python-catkin-tools build-essential -y
            source `find /opt/ros -name setup.bash | sort | head -1` && echo $ROS_DISTRO
            rosdep install --from-paths . --ignore-src -y
            cd .. && catkin init
      - run:
          name: Build
          command: |
            catkin build
      - run:
          name: Run Tests
          command: |
            catkin run_tests
    working_directory: ~/src

  kinetic:
    docker:
      - image: ros:kinetic-ros-core
    steps:
      - checkout
      - run: echo "Kinetic build."

workflows:
  version: 2
  ros_build:
    jobs:
      - indigo
      - kinetic
